# Jupyter Setup

In [1]:
x = 10
print(x)

10


# Part A: Reproduce the hidden-state bug

In [2]:
# print(name)

In [3]:
name = "Timothious"

# signature and docstring

In [4]:
np.reshape?

Object `np.reshape` not found.


# Measure performance.

In [5]:
%timeit sum(range(1000))

14.5 μs ± 346 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
%%time

total = 0

for i in range(1000000):
    total += i
print(f"Total: {total}")

Total: 499999500000
CPU times: user 131 ms, sys: 13 μs, total: 131 ms
Wall time: 129 ms


# Part B: NumPy Experiment

Today we will compare Python lists with NumPy arrays.

In [7]:
import numpy as np

In [8]:
arr = np.array([1, 2, 3, 4])

In [9]:
# Python List:
# It is a general-purpose container.
numbers = [1, 2, 3, 4]

In [10]:
# NumPy array:
# It is a general-purpose container.
numbers_arr= np.array([1, 2, 3, 4])

In [11]:
# So it can operate on the entire array without writing a Python loop.
print(numbers_arr *2)

[2 4 6 8]


In [12]:
arr = np.zeros((3, 4))
# 3 rows × 4 columns
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Use of np.arange()

In [13]:
print(np.arange(0, 10, 2))
print(np.arange(0,10,4))
print(np.arange(5, -5, -2))

[0 2 4 6 8]
[0 4 8]
[ 5  3  1 -1 -3]


#### Use of np.linspace()

In [14]:
print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


#### .shape, .dtype, .size

In [15]:
arr_shape = np.zeros((3, 4))
print(arr_shape.shape)

(3, 4)


In [16]:
print(arr_shape.dtype)

float64


In [17]:
print(arr_shape.size)

12


#### Indexing and Slicing

In [18]:
arr_index = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# First Row
print(arr_index[0])
# Forst Column
print(arr_index[:, 0])

[1 2 3]
[1 4 7]


In [19]:
print(arr_index[1,2])

6


#### Boolean Masking

In [20]:
arr_bool = np.array([1, 3, 6, 8, 2])
print(arr_bool > 5)

[False False  True  True False]


In [21]:
print(arr_bool[arr_bool > 5])
print(arr_bool)

[6 8]
[1 3 6 8 2]


#### Broadcasting

In [22]:
arr_broad = np.array([10,20,30])
print("Otiginal:", arr_broad)
print("After Broadcast: ", arr_broad + 5)

Otiginal: [10 20 30]
After Broadcast:  [15 25 35]


#### Axis

In [23]:
arr_axis = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
'''
axis=0 → collapse rows → column results

axis=1 → collapse columns → row results
'''
print(arr_axis.mean(axis=0))
print(arr_axis.mean(axis=1))

[4. 5. 6.]
[2. 5. 8.]


#### Reshape

In [24]:
arr_shape = np.arange(12)
print(f'Original: {arr_shape}')
new_arr = arr_shape.reshape(3, 4)
print(f'Re Shaped: {new_arr}')

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Re Shaped: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
